name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  venv:
    runs-on: ubuntu-latest

    steps:
    - name: create venv
      run: |
        python3 -m venv venv
        source venv/bin/activate


  build:

    runs-on: ubuntu-latest
    needs: [ venv ]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t python-docker .

    - name: Run Container
      run: docker run --name teste -p 8000:8000 -d python-docker

    - name: Get container running
      run: docker ps
    
    - name: Get container logs
      run: docker logs teste

  