name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: venv
      run: sudo python -m venv /home/runner/work/Infra-PlayGround/Infra-PlayGround/venv

    - name: Build the Docker image
      run: docker build -t python-docker .

    - name: Run Container
      run: docker run --name teste -d -p 8000:8000 python-docker

    - name: Get container running
      run: docker ps
    
    - name: Get container logs
      run: docker logs teste
      
    - name: Sleep
      run: sleep 5s
      
    - name: Check HTTP status of production site
      id: code
      run: curl --include http:/localhost:8000/ | head -n 1
    - uses: nick-invision/assert-action@v1
      with:
        expected: 200
        actual:  ${{ steps.code.outputs.status }}
