name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:


  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t python-docker .

    - name: Run Container
      run: docker run --name teste -p 8000:8000 -d python-docker

    - name: Get container running
      run: docker ps
    
    - name: Get container logs
      run: docker logs teste

    - name: Test main route
      id: mainRoute
      run: echo "::set-output name=status::$(curl -o /dev/null -s -w "%{http_code}\n" localhost:8080)"
  