name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: venv
      run: sudo python -m venv venv
    - name: activate venv
      run: source /venv/bin/activate.csh
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t python-docker .

    - name: Run Container
      run: docker run --name teste -p 8000:8000 -d python-docker

    - name: Get container running
      run: ls -a
    
    - name: Get container logs
      run: docker logs teste

  
