name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: venv
      run: sudo python -m venv /home/runner/work/Infra-PlayGround/Infra-PlayGround/venv
    - name: activate
      run: /home/runner/work/Infra-PlayGround/Infra-PlayGround/venv/bin/activate.ps1
    - name: Build the Docker image
      run: docker build -t python-docker .

    - name: Run Container
      run: docker run --name teste -p 8000:8000 -d python-docker

    - name: Get container running
      run: ls -a
    
    - name: Get container logs
      run: docker logs teste

  
